### ISSUE TITLE
AzDO Build and Release Pipelines

### ISSUE THREAD

**Issue by analogrelay** [Pilchie/DependencyFlow#6]
It would be nice if we could just make changes and flow them through to production using Azure DevOps. I'm happy to sign up to do this work, unless you'd like to explore the tooling/etc. experience yourself ;).

Another thing to consider would be if we want to move this app to a quasi "official" place. I don't really see a problem with having something like this in the aspnet org. Or we could put it in an AzDO Git Repository. I'm also fine leaving it here 🤷‍♂.

**Comment by Pilchie** [comment]
I set up a GitHub action based on the default template, but not sure what triggers to use to do a deploy, and not sure how to manage secrets.

**Comment by analogrelay** [comment]
Yeah, that's one of the challenges with GitHub actions. An AzDO pipeline does have the benefit of cleaner Azure auth.

**Comment by Pilchie** [comment]
This was done (via GH Actions) in #16, #17, #18, and #19
